# Generated by Django 3.2.9 on 2022-03-20 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_default', models.BooleanField(default=False, verbose_name='Показывать по умлочанию')),
                ('name', models.CharField(max_length=255, verbose_name='Название города')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_on_index', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена')),
                ('image_small', models.ImageField(blank=True, null=True, upload_to='static/img/products/', verbose_name='Маленькое фото товара')),
                ('image_big', models.ImageField(blank=True, null=True, upload_to='static/img/products/', verbose_name='Большое фото товара')),
                ('count', models.PositiveIntegerField(default=0, null=True, verbose_name='Количество')),
                ('active', models.BooleanField(default=False, verbose_name='Флаг активности')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='Отзыв')),
                ('author', models.CharField(max_length=255, verbose_name='ФИО')),
                ('image', models.ImageField(upload_to='static/img/reviews/', verbose_name='Изображение')),
                ('active', models.BooleanField(default=False, verbose_name='Флаг активности')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(help_text='Формат ссылки: "https://www.youtube.com/watch?v=otCL-UXvcvo"', max_length=255, verbose_name='Ссылка на видео')),
                ('coords', models.CharField(help_text='Формат данных: "55.71, 89.99"', max_length=255, verbose_name='Координаты метки на карте')),
                ('balloon_text', models.TextField(verbose_name='Контент балуна на карте')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='testapp.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
